// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
lv_obj_t * ui_Screen0;
lv_obj_t * ui_LabelHelloPilot;
lv_obj_t * ui_LabelAllSystemReady;
void ui_event_ButtonToScn1(lv_event_t * e);
lv_obj_t * ui_ButtonToScn1;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_ArcWater;
void ui_event_ArcOil(lv_event_t * e);
lv_obj_t * ui_ArcOil;
lv_obj_t * ui_LabelOil;
lv_obj_t * ui_LabelWater;
lv_obj_t * ui_LabelOilValue;
lv_obj_t * ui_LabelWaterValue;
lv_obj_t * ui_HorLine3;
lv_obj_t * ui_puntini3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
void ui_event_ButtonToScn2(lv_event_t * e);
lv_obj_t * ui_ButtonToScn2;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_HorLine1;
lv_obj_t * ui_VertLine;
lv_obj_t * ui_LabelFuelPressure;
lv_obj_t * ui_LabelRight;
lv_obj_t * ui_LabelLeft;
lv_obj_t * ui_LabelFuelPressureValue;
lv_obj_t * ui_labelpsi;
lv_obj_t * ui_ArcFuelRight;
lv_obj_t * ui_ArcFuelLeft;
lv_obj_t * ui_BarFuelPressure;
lv_obj_t * ui_label01;
lv_obj_t * ui_label02;
lv_obj_t * ui_LabelLeftValue;
lv_obj_t * ui_LabelRightValue;
lv_obj_t * ui_puntini2;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
void ui_event_ButtonToScn3(lv_event_t * e);
lv_obj_t * ui_ButtonToScn3;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_PanelGearColor;
lv_obj_t * ui_Arc6;
lv_obj_t * ui_VertLine2;
lv_obj_t * ui_ArcFlapAngle;
lv_obj_t * ui_ArcFlap;
lv_obj_t * ui_HorLine4;
lv_obj_t * ui_LabelFlapDown;
lv_obj_t * ui_LabelGear;
lv_obj_t * ui_LabelSpeed;
lv_obj_t * ui_LabelSpeedValue;
lv_obj_t * ui_ArcSpeed;
lv_obj_t * ui_label2;
lv_obj_t * ui_LabelFlapLine;
lv_obj_t * ui_LabelPosition;
lv_obj_t * ui_LabelPositionValue;
lv_obj_t * ui_puntini4;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Panel13;
void ui_event_ButtonToScn4(lv_event_t * e);
lv_obj_t * ui_ButtonToScn4;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_ArcSpeed1;
lv_obj_t * ui_LabelAltitude;
lv_obj_t * ui_LabelSpeed1;
lv_obj_t * ui_LabelAltitudeValue;
lv_obj_t * ui_LabelSpeedValue1;
lv_obj_t * ui_HorLine2;
lv_obj_t * ui_LabelQNHValue;
lv_obj_t * ui_LabelQNH;
lv_obj_t * ui_puntini5;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel19;
void ui_event_ButtonToSc1(lv_event_t * e);
lv_obj_t * ui_ButtonToSc1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonToScn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen1_screen_init);
        changeScreenTo1(e);
    }
}
void ui_event_ArcOil(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_arc_increment(ui_ArcOil, 1);
    }
}
void ui_event_ButtonToScn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen2_screen_init);
        changeScreenTo2(e);
    }
}
void ui_event_ButtonToScn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen3_screen_init);
        changeScreenTo3(e);
    }
}
void ui_event_ButtonToScn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen4_screen_init);
        changeScreenTo4(e);
    }
}
void ui_event_ButtonToSc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen1_screen_init);
        changeScreenTo1(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen0_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen0);
}
