// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#ifndef _GAUGE2_UI_H
#define _GAUGE2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_LabelHelloPilot;
extern lv_obj_t * ui_LabelAllSystemReady;
void ui_event_ButtonToScn1(lv_event_t * e);
extern lv_obj_t * ui_ButtonToScn1;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ArcWater;
void ui_event_ArcOil(lv_event_t * e);
extern lv_obj_t * ui_ArcOil;
extern lv_obj_t * ui_LabelOil;
extern lv_obj_t * ui_LabelWater;
extern lv_obj_t * ui_LabelOilValue;
extern lv_obj_t * ui_LabelWaterValue;
extern lv_obj_t * ui_HorLine3;
extern lv_obj_t * ui_puntini3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
void ui_event_ButtonToScn2(lv_event_t * e);
extern lv_obj_t * ui_ButtonToScn2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_HorLine1;
extern lv_obj_t * ui_VertLine;
extern lv_obj_t * ui_LabelFuelPressure;
extern lv_obj_t * ui_LabelRight;
extern lv_obj_t * ui_LabelLeft;
extern lv_obj_t * ui_LabelFuelPressureValue;
extern lv_obj_t * ui_labelpsi;
extern lv_obj_t * ui_ArcFuelRight;
extern lv_obj_t * ui_ArcFuelLeft;
extern lv_obj_t * ui_BarFuelPressure;
extern lv_obj_t * ui_label01;
extern lv_obj_t * ui_label02;
extern lv_obj_t * ui_LabelLeftValue;
extern lv_obj_t * ui_LabelRightValue;
extern lv_obj_t * ui_puntini2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
void ui_event_ButtonToScn3(lv_event_t * e);
extern lv_obj_t * ui_ButtonToScn3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_PanelGearColor;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_VertLine2;
extern lv_obj_t * ui_ArcFlapAngle;
extern lv_obj_t * ui_ArcFlap;
extern lv_obj_t * ui_HorLine4;
extern lv_obj_t * ui_LabelFlapDown;
extern lv_obj_t * ui_LabelGear;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_LabelSpeedValue;
extern lv_obj_t * ui_ArcSpeed;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_LabelFlapLine;
extern lv_obj_t * ui_LabelPosition;
extern lv_obj_t * ui_LabelPositionValue;
extern lv_obj_t * ui_puntini4;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
void ui_event_ButtonToScn4(lv_event_t * e);
extern lv_obj_t * ui_ButtonToScn4;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_ArcSpeed1;
extern lv_obj_t * ui_LabelAltitude;
extern lv_obj_t * ui_LabelSpeed1;
extern lv_obj_t * ui_LabelAltitudeValue;
extern lv_obj_t * ui_LabelSpeedValue1;
extern lv_obj_t * ui_HorLine2;
extern lv_obj_t * ui_LabelQNHValue;
extern lv_obj_t * ui_LabelQNH;
extern lv_obj_t * ui_puntini5;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
void ui_event_ButtonToSc1(lv_event_t * e);
extern lv_obj_t * ui_ButtonToSc1;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
