// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void changeScreenTo1(lv_event_t * e);
void changeScreenTo2(lv_event_t * e);
void changeScreenTo3(lv_event_t * e);
void changeScreenTo4(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
