// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#include "ui.h"

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHelloPilot = lv_label_create(ui_Screen0);
    lv_obj_set_width(ui_LabelHelloPilot, 337);
    lv_obj_set_height(ui_LabelHelloPilot, 40);
    lv_obj_set_x(ui_LabelHelloPilot, -3);
    lv_obj_set_y(ui_LabelHelloPilot, 2);
    lv_obj_set_align(ui_LabelHelloPilot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHelloPilot, "HELLO PILOT");
    lv_obj_set_style_text_align(ui_LabelHelloPilot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHelloPilot, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAllSystemReady = lv_label_create(ui_Screen0);
    lv_obj_set_width(ui_LabelAllSystemReady, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAllSystemReady, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAllSystemReady, 3);
    lv_obj_set_y(ui_LabelAllSystemReady, 33);
    lv_obj_set_align(ui_LabelAllSystemReady, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAllSystemReady, "ALL SYSTEM READY");
    lv_obj_set_style_text_color(ui_LabelAllSystemReady, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAllSystemReady, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAllSystemReady, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonToScn1 = lv_button_create(ui_Screen0);
    lv_obj_set_width(ui_ButtonToScn1, 480);
    lv_obj_set_height(ui_ButtonToScn1, 480);
    lv_obj_set_align(ui_ButtonToScn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToScn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonToScn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToScn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToScn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonToScn1, ui_event_ButtonToScn1, LV_EVENT_ALL, NULL);

}
