// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelGearColor = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelGearColor, 534);
    lv_obj_set_height(ui_PanelGearColor, 250);
    lv_obj_set_x(ui_PanelGearColor, 1);
    lv_obj_set_y(ui_PanelGearColor, -129);
    lv_obj_set_align(ui_PanelGearColor, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelGearColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelGearColor, lv_color_hex(0x069729), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGearColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc6 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Arc6, 480);
    lv_obj_set_height(ui_Arc6, 480);
    lv_obj_set_x(ui_Arc6, 0);
    lv_obj_set_y(ui_Arc6, -4);
    lv_obj_set_align(ui_Arc6, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc6, 95, 295);
    lv_arc_set_value(ui_Arc6, 0);
    lv_arc_set_bg_angles(ui_Arc6, 180, 360);
    lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc6, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc6, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc6, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VertLine2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_VertLine2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VertLine2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VertLine2, 0);
    lv_obj_set_y(ui_VertLine2, 240);
    lv_obj_set_align(ui_VertLine2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VertLine2,
                      "|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|");
    lv_obj_set_style_text_letter_space(ui_VertLine2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_VertLine2, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_VertLine2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcFlapAngle = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcFlapAngle, 480);
    lv_obj_set_height(ui_ArcFlapAngle, 480);
    lv_obj_set_align(ui_ArcFlapAngle, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcFlapAngle, 0, 45);
    lv_arc_set_value(ui_ArcFlapAngle, 45);
    lv_arc_set_bg_angles(ui_ArcFlapAngle, 0, 45);
    lv_obj_set_style_arc_width(ui_ArcFlapAngle, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFlapAngle, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcFlapAngle, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFlapAngle, 70, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcFlapAngle, 240, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFlapAngle, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcFlapAngle, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcFlapAngle, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcFlap = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcFlap, 480);
    lv_obj_set_height(ui_ArcFlap, 480);
    lv_obj_set_align(ui_ArcFlap, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcFlap, 0, 45);
    lv_arc_set_value(ui_ArcFlap, 45);
    lv_arc_set_bg_angles(ui_ArcFlap, 0, 45);
    lv_obj_set_style_arc_width(ui_ArcFlap, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFlap, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcFlap, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcFlap, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcFlap, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcFlap, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcFlap, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcFlap, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HorLine4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_HorLine4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HorLine4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HorLine4, 0);
    lv_obj_set_y(ui_HorLine4, -7);
    lv_obj_set_align(ui_HorLine4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HorLine4, "______________________________________________________________________");

    ui_LabelFlapDown = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelFlapDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlapDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFlapDown, 2);
    lv_obj_set_y(ui_LabelFlapDown, -125);
    lv_obj_set_align(ui_LabelFlapDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFlapDown, "DOWN");
    lv_obj_set_style_text_font(ui_LabelFlapDown, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGear = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGear, 2);
    lv_obj_set_y(ui_LabelGear, -91);
    lv_obj_set_align(ui_LabelGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGear, "GEAR");
    lv_obj_set_style_text_font(ui_LabelGear, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, -70);
    lv_obj_set_y(ui_LabelSpeed, 107);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed, "SPEED");
    lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedValue = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeedValue, -75);
    lv_obj_set_y(ui_LabelSpeedValue, 78);
    lv_obj_set_align(ui_LabelSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedValue, "252");
    lv_obj_set_style_text_font(ui_LabelSpeedValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcSpeed = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_ArcSpeed, 480);
    lv_obj_set_height(ui_ArcSpeed, 480);
    lv_obj_set_x(ui_ArcSpeed, -4);
    lv_obj_set_y(ui_ArcSpeed, -2);
    lv_obj_set_align(ui_ArcSpeed, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcSpeed, 0, 330);
    lv_arc_set_value(ui_ArcSpeed, 252);
    lv_arc_set_bg_angles(ui_ArcSpeed, 0, 80);
    lv_arc_set_mode(ui_ArcSpeed, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_ArcSpeed, 90);
    lv_obj_set_style_arc_width(ui_ArcSpeed, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0xFF9100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpeed, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label2, -215);
    lv_obj_set_y(ui_label2, 16);
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "KM/H");
    lv_obj_set_style_text_font(ui_label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlapLine = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelFlapLine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlapLine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFlapLine, 0);
    lv_obj_set_y(ui_LabelFlapLine, 240);
    lv_obj_set_align(ui_LabelFlapLine, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFlapLine,
                      "|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|");
    lv_obj_set_style_text_letter_space(ui_LabelFlapLine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelFlapLine, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_LabelFlapLine, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosition = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelPosition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosition, 69);
    lv_obj_set_y(ui_LabelPosition, 107);
    lv_obj_set_align(ui_LabelPosition, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPosition, "POSITION");
    lv_obj_set_style_text_font(ui_LabelPosition, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPositionValue = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelPositionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPositionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPositionValue, 65);
    lv_obj_set_y(ui_LabelPositionValue, 78);
    lv_obj_set_align(ui_LabelPositionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPositionValue, "45°");
    lv_obj_set_style_text_font(ui_LabelPositionValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_puntini4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_puntini4, 126);
    lv_obj_set_height(ui_puntini4, 32);
    lv_obj_set_x(ui_puntini4, 0);
    lv_obj_set_y(ui_puntini4, 164);
    lv_obj_set_align(ui_puntini4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_puntini4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_puntini4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_puntini4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_puntini4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_puntini4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_puntini4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_puntini4);
    lv_obj_set_width(ui_Panel15, 15);
    lv_obj_set_height(ui_Panel15, 15);
    lv_obj_set_x(ui_Panel15, 10);
    lv_obj_set_y(ui_Panel15, 0);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_puntini4);
    lv_obj_set_width(ui_Panel10, 15);
    lv_obj_set_height(ui_Panel10, 15);
    lv_obj_set_x(ui_Panel10, -10);
    lv_obj_set_y(ui_Panel10, 0);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_puntini4);
    lv_obj_set_width(ui_Panel12, 15);
    lv_obj_set_height(ui_Panel12, 15);
    lv_obj_set_x(ui_Panel12, -30);
    lv_obj_set_y(ui_Panel12, 0);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_puntini4);
    lv_obj_set_width(ui_Panel13, 15);
    lv_obj_set_height(ui_Panel13, 15);
    lv_obj_set_x(ui_Panel13, 30);
    lv_obj_set_y(ui_Panel13, 0);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonToScn4 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonToScn4, 480);
    lv_obj_set_height(ui_ButtonToScn4, 480);
    lv_obj_set_x(ui_ButtonToScn4, 1);
    lv_obj_set_y(ui_ButtonToScn4, 2);
    lv_obj_set_align(ui_ButtonToScn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToScn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonToScn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToScn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToScn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonToScn4, ui_event_ButtonToScn4, LV_EVENT_ALL, NULL);

}
