// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcWater = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcWater, 480);
    lv_obj_set_height(ui_ArcWater, 480);
    lv_obj_set_x(ui_ArcWater, 0);
    lv_obj_set_y(ui_ArcWater, -4);
    lv_obj_set_align(ui_ArcWater, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcWater, 60, 200);
    lv_arc_set_value(ui_ArcWater, 135);
    lv_arc_set_bg_angles(ui_ArcWater, 180, 360);
    lv_obj_set_style_arc_width(ui_ArcWater, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcWater, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcWater, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcWater, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcWater, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcWater, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcOil = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcOil, 480);
    lv_obj_set_height(ui_ArcOil, 480);
    lv_obj_set_x(ui_ArcOil, 0);
    lv_obj_set_y(ui_ArcOil, 5);
    lv_obj_set_align(ui_ArcOil, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcOil, 0, 180);
    lv_arc_set_value(ui_ArcOil, 120);
    lv_arc_set_bg_angles(ui_ArcOil, 360, 180);
    lv_arc_set_mode(ui_ArcOil, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_width(ui_ArcOil, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcOil, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcOil, lv_color_hex(0xF04F1B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcOil, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcOil, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcOil, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcOil, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcOil, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelOil = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelOil, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOil, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOil, 3);
    lv_obj_set_y(ui_LabelOil, 33);
    lv_obj_set_align(ui_LabelOil, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOil, "OIL");
    lv_obj_set_style_text_color(ui_LabelOil, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOil, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWater = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWater, 5);
    lv_obj_set_y(ui_LabelWater, -55);
    lv_obj_set_align(ui_LabelWater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWater, "WATER");
    lv_obj_set_style_text_font(ui_LabelWater, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOilValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelOilValue, 125);
    lv_obj_set_height(ui_LabelOilValue, 40);
    lv_obj_set_x(ui_LabelOilValue, 0);
    lv_obj_set_y(ui_LabelOilValue, 60);
    lv_obj_set_align(ui_LabelOilValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOilValue, "120°");
    lv_obj_set_style_text_align(ui_LabelOilValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOilValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWaterValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWaterValue, 125);
    lv_obj_set_height(ui_LabelWaterValue, 40);
    lv_obj_set_x(ui_LabelWaterValue, 0);
    lv_obj_set_y(ui_LabelWaterValue, -88);
    lv_obj_set_align(ui_LabelWaterValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWaterValue, "195°");
    lv_obj_set_style_text_align(ui_LabelWaterValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWaterValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorLine3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HorLine3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HorLine3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HorLine3, 7);
    lv_obj_set_y(ui_HorLine3, -4);
    lv_obj_set_align(ui_HorLine3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HorLine3, "____________________________________");

    ui_puntini3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_puntini3, 126);
    lv_obj_set_height(ui_puntini3, 32);
    lv_obj_set_x(ui_puntini3, 0);
    lv_obj_set_y(ui_puntini3, 164);
    lv_obj_set_align(ui_puntini3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_puntini3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_puntini3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_puntini3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_puntini3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_puntini3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_puntini3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_puntini3);
    lv_obj_set_width(ui_Panel4, 15);
    lv_obj_set_height(ui_Panel4, 15);
    lv_obj_set_x(ui_Panel4, -30);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_puntini3);
    lv_obj_set_width(ui_Panel5, 15);
    lv_obj_set_height(ui_Panel5, 15);
    lv_obj_set_x(ui_Panel5, -10);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_puntini3);
    lv_obj_set_width(ui_Panel6, 15);
    lv_obj_set_height(ui_Panel6, 15);
    lv_obj_set_x(ui_Panel6, 10);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_puntini3);
    lv_obj_set_width(ui_Panel7, 15);
    lv_obj_set_height(ui_Panel7, 15);
    lv_obj_set_x(ui_Panel7, 30);
    lv_obj_set_y(ui_Panel7, 0);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonToScn2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonToScn2, 480);
    lv_obj_set_height(ui_ButtonToScn2, 480);
    lv_obj_set_align(ui_ButtonToScn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToScn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonToScn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToScn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToScn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcOil, ui_event_ArcOil, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonToScn2, ui_event_ButtonToScn2, LV_EVENT_ALL, NULL);

}
