// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Gauge2

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcSpeed1 = lv_arc_create(ui_Screen4);
    lv_obj_set_width(ui_ArcSpeed1, 480);
    lv_obj_set_height(ui_ArcSpeed1, 480);
    lv_obj_set_x(ui_ArcSpeed1, 0);
    lv_obj_set_y(ui_ArcSpeed1, -4);
    lv_obj_set_align(ui_ArcSpeed1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcSpeed1, 0, 330);
    lv_arc_set_value(ui_ArcSpeed1, 252);
    lv_arc_set_bg_angles(ui_ArcSpeed1, 180, 360);
    lv_obj_set_style_arc_width(ui_ArcSpeed1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSpeed1, lv_color_hex(0xFF9100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSpeed1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcSpeed1, 60, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcSpeed1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSpeed1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSpeed1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelAltitude = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelAltitude, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAltitude, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAltitude, 3);
    lv_obj_set_y(ui_LabelAltitude, 33);
    lv_obj_set_align(ui_LabelAltitude, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAltitude, "ALTITUDE");
    lv_obj_set_style_text_color(ui_LabelAltitude, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAltitude, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAltitude, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelSpeed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed1, 5);
    lv_obj_set_y(ui_LabelSpeed1, -55);
    lv_obj_set_align(ui_LabelSpeed1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed1, "SPEED");
    lv_obj_set_style_text_font(ui_LabelSpeed1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAltitudeValue = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelAltitudeValue, 125);
    lv_obj_set_height(ui_LabelAltitudeValue, 40);
    lv_obj_set_x(ui_LabelAltitudeValue, 0);
    lv_obj_set_y(ui_LabelAltitudeValue, 60);
    lv_obj_set_align(ui_LabelAltitudeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAltitudeValue, "1200");
    lv_obj_set_style_text_align(ui_LabelAltitudeValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAltitudeValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedValue1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelSpeedValue1, 125);
    lv_obj_set_height(ui_LabelSpeedValue1, 40);
    lv_obj_set_x(ui_LabelSpeedValue1, 0);
    lv_obj_set_y(ui_LabelSpeedValue1, -88);
    lv_obj_set_align(ui_LabelSpeedValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedValue1, "252");
    lv_obj_set_style_text_align(ui_LabelSpeedValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedValue1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorLine2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_HorLine2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HorLine2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HorLine2, 7);
    lv_obj_set_y(ui_HorLine2, -4);
    lv_obj_set_align(ui_HorLine2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HorLine2, "____________________________________");

    ui_LabelQNHValue = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelQNHValue, 125);
    lv_obj_set_height(ui_LabelQNHValue, 40);
    lv_obj_set_x(ui_LabelQNHValue, 0);
    lv_obj_set_y(ui_LabelQNHValue, 130);
    lv_obj_set_align(ui_LabelQNHValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelQNHValue, "1024");
    lv_obj_set_style_text_align(ui_LabelQNHValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelQNHValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelQNH = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelQNH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelQNH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelQNH, 4);
    lv_obj_set_y(ui_LabelQNH, 101);
    lv_obj_set_align(ui_LabelQNH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelQNH, "QNH");
    lv_obj_set_style_text_color(ui_LabelQNH, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelQNH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelQNH, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_puntini5 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_puntini5, 126);
    lv_obj_set_height(ui_puntini5, 32);
    lv_obj_set_x(ui_puntini5, 0);
    lv_obj_set_y(ui_puntini5, 164);
    lv_obj_set_align(ui_puntini5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_puntini5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_puntini5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_puntini5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_puntini5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_puntini5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_puntini5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_puntini5);
    lv_obj_set_width(ui_Panel16, 15);
    lv_obj_set_height(ui_Panel16, 15);
    lv_obj_set_x(ui_Panel16, 30);
    lv_obj_set_y(ui_Panel16, 0);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_puntini5);
    lv_obj_set_width(ui_Panel17, 15);
    lv_obj_set_height(ui_Panel17, 15);
    lv_obj_set_x(ui_Panel17, -10);
    lv_obj_set_y(ui_Panel17, 0);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_puntini5);
    lv_obj_set_width(ui_Panel18, 15);
    lv_obj_set_height(ui_Panel18, 15);
    lv_obj_set_x(ui_Panel18, 10);
    lv_obj_set_y(ui_Panel18, 0);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_puntini5);
    lv_obj_set_width(ui_Panel19, 15);
    lv_obj_set_height(ui_Panel19, 15);
    lv_obj_set_x(ui_Panel19, -30);
    lv_obj_set_y(ui_Panel19, 0);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonToSc1 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonToSc1, 480);
    lv_obj_set_height(ui_ButtonToSc1, 480);
    lv_obj_set_align(ui_ButtonToSc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToSc1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonToSc1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonToSc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonToSc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonToSc1, ui_event_ButtonToSc1, LV_EVENT_ALL, NULL);

}
